/**
 * Curated, age-appropriate words (Story Mode never uses more than 5 letters).
 * Everything here is data: a backend can replace or extend these pools.
 */
export const WORD_BANK: Record<number, string[]> = {
  2: [],
  3: ["CAT", "DOG", "SUN", "HAT", "BAT", "CUP", "BUS", "PEN", "BED", "MAP", "FAN", "FOX", "BOX", "PIG", "COW", "HEN"],
  4: ["FISH", "BIRD", "TREE", "STAR", "MOON", "RAIN", "BOOK", "FROG", "DUCK", "BALL", "CAKE", "MILK", "FIRE"],
  5: ["WATER", "APPLE", "PLANT", "HORSE", "TIGER", "BREAD", "CLOUD", "GRASS", "HOUSE", "MOUSE", "SHEEP", "SNAKE", "TRAIN", "BEACH", "SMILE"],
};

/**
 * Extra real words used ONLY to avoid ambiguous questions: if swapping in a
 * distractor letter makes another real word (C_T → CUT), that distractor is
 * rejected so there is never a second right answer.
 */
const EXTRA_VALID_WORDS = `ARM ANT APE BAG BEE BIG BUG CAP CAR COT CUT DIG DIM DIP DOT DRY EAR EAT EGG END EYE FIG FIT FLY GUM HID HIM HIP HIT HOP
HOT HUG HUT ICE INK JAM JAR JET JOG JOY KEY KID KIT LAP LEG LID LIP LOG LOT MAD MAT MEN MIX MUD MUG NAP NET NOT NUT OIL OLD
OWL PAD PAN PAT PET PIE PIN POT RAG RAN RAT RED RIB RIP ROB ROD RUB RUG RUN SAD SAT SAW SAY SEA SET SHE SIT SIX SKY SUM TAB
TAG TAN TAP TEA TEN TIN TIP TOE TOP TOY TUB VAN WEB WET WIN YES ZIP BAD BAN BAR BAY BIT BOW BOY BUD BUN BUY CAB CAN COD COP
DAD DEN DID DOE DUG FAT FED FEW FIN FIR FIX FOG FUN GAP GAS GOT GUN GUY HAM HAS HER HEY HID HOW JAW LAW LAY LED LET LIE MOM
MOP NAG NEW NIL NOD NOR NOW OAK OAR ODD OFF OUR OUT OWN PAW PAY PEA PEG PIG PIT PLY POP PUB PUN PUT RAY RIM ROW SAP SIP SOB
SON SOW SPA SPY STY SUB SUE TAR TIE TON TOO TRY URN USE VET WAG WAR WAX WAY WHO WHY WIG WON WOO YAK YAM YAP YEN YET YOU ZOO
FISH BIRD TREE STAR MOON RAIN BOOK FROG DUCK BALL CAKE MILK FIRE BEAR BELL BOAT BONE CAMP CARD CART CORN DOLL DOOR DRUM FARM
FEET FOOD FORK GAME GIFT GOAT HAND HOME JUMP KING KITE LAMP LEAF LION LOVE MAKE NEST PARK PLAY POND RING ROAD ROCK SAND SEED
SHIP SHOE SING SNOW SOAP SOCK SOUP SWIM TAIL TOYS WIND WING WOOD WORM YARD ZERO BAKE BARN BEAN BIKE BLUE COAT COOK DARK DESK
DIRT DIVE DOWN DUST EACH FAST FLAG FLAT FLOW GLAD GOLD GOOD GROW HAIR HALF HELP HIDE HILL HOLE HUNT JOKE KEEP KICK KIND LAKE
LAND LATE LEFT LIFT LIKE LINE LIST LOOK LOUD MAIL MEAT MEET MINE MOVE NAME NEAR NICE NOSE OPEN PAGE PAIR PATH PICK PINK PULL
RACE READ REAL REST RICE RIDE ROLL ROOM ROSE RULE SAFE SAIL SAME SEAT SHOP SHOW SIDE SIZE SLOW SOFT SOME SONG STEP STOP SURE
TAKE TALK TALL TEAM TELL THAN THAT THEM THEN THEY THIS TIME TINY TOWN TURN VERY WAIT WALK WALL WARM WASH WAVE WELL WENT WERE
WHAT WHEN WILL WISH WITH WORK YOUR
WATER APPLE PLANT HORSE TIGER BREAD CLOUD GRASS HOUSE MOUSE SHEEP SNAKE TRAIN BEACH SMILE CHAIR CLOCK DANCE DREAM EARTH FLOOR
FRUIT GLASS HAPPY HEART LAUGH LEMON LIGHT MONEY MUSIC NIGHT OCEAN PAPER PARTY PIZZA QUEEN RIVER ROBOT SHEEP SLEEP SPOON STONE
STORY SUGAR TABLE TEETH TOAST TOUCH TOWER WHALE WHEEL WHITE WORLD YOUNG ZEBRA BLACK BROWN GREEN ORANGE`.split(/\s+/);

export const VALID_WORDS: ReadonlySet<string> = new Set([...EXTRA_VALID_WORDS, ...Object.values(WORD_BANK).flat()]);

export const ALPHABET = [..."ABCDEFGHIJKLMNOPQRSTUVWXYZ"];

/** Letters that look alike, offered as distractors on harder levels. */
export const LOOKALIKES: Record<string, string> = {
  B: "DPR", D: "BPO", P: "BQR", Q: "OPG", M: "NW", N: "MHU", U: "VYN", V: "UYW", E: "FLB", F: "ETP", I: "LJT", L: "IJT", C: "GOE",
  G: "CQO", O: "CDQ", T: "FIY", H: "NAK", A: "OHR", R: "BPK", S: "ZC", Z: "SN", W: "MV", Y: "VU", K: "HRX", X: "KY", J: "IL",
};
